//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObyvEntities : DbContext
    {
        private static ObyvEntities _context;
        public ObyvEntities()
            : base("name=ObyvEntities")
        {
        }
        public static ObyvEntities GetContext()
        {
            if (_context == null)
                _context = new ObyvEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategor> Kategors { get; set; }
        public virtual DbSet<NameTovar> NameTovars { get; set; }
        public virtual DbSet<Postavchik> Postavchiks { get; set; }
        public virtual DbSet<Proizvoditel> Proizvoditels { get; set; }
        public virtual DbSet<PunctVidachi> PunctVidachis { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatysZakaz> StatysZakazs { get; set; }
        public virtual DbSet<Tovar> Tovars { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zakaz> Zakazs { get; set; }
        public virtual DbSet<TovarZakaz> TovarZakazs { get; set; }
    }
}
