//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int IDTovar { get; set; }
        public string Articul { get; set; }
        public Nullable<int> Name { get; set; }
        public string EdinichaIzmerenia { get; set; }
        public Nullable<int> Chena { get; set; }
        public Nullable<int> Postavchik { get; set; }
        public Nullable<int> Proizvoditel { get; set; }
        public Nullable<int> KategoriaTovar { get; set; }
        public Nullable<int> DeistvuichaiaSkidka { get; set; }
        public Nullable<int> KolVoNaSklade { get; set; }
        public string OpisanieTovara { get; set; }
        public string Foto { get; set; }

        public string PhotoPath
        {
            get
            {
                if (!string.IsNullOrEmpty(Foto))
                    return $"/Images/{this.Foto}";
                return "/Images/picture.png";
            }
        }

        public virtual Kategor Kategor { get; set; }
        public virtual NameTovar NameTovar { get; set; }
        public virtual Postavchik Postavchik1 { get; set; }
        public virtual Proizvoditel Proizvoditel1 { get; set; }
        public virtual TovarZakaz TovarZakaz { get; set; }
    }
}
