//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.TovarZakazs = new HashSet<TovarZakaz>();
        }
    
        public int NomerZakaza { get; set; }
        public Nullable<System.DateTime> DataZakaza { get; set; }
        public Nullable<System.DateTime> DataDostavki { get; set; }
        public Nullable<int> AdresPunktaVidachi { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> KodDlaPoluchenia { get; set; }
        public Nullable<int> StatusZakaza { get; set; }
    
        public virtual PunctVidachi PunctVidachi { get; set; }
        public virtual StatysZakaz StatysZakaz { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarZakaz> TovarZakazs { get; set; }
    }
}
